const { chromium } = require('playwright');
const out = process.env.OUT || '/tmp/uc';
const base = process.env.BASE || 'http://127.0.0.1:4317/';
require('fs').mkdirSync(out, { recursive: true });

(async () => {
  const b = await chromium.launch();
  const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
  const errs = [];
  p.on('pageerror', (e) => errs.push(`pageerror: ${e.message}`));
  p.on('console', (m) => { if (m.type() === 'error' && !/fonts\.g|ERR_TUNNEL|net::ERR/.test(m.text())) errs.push(`console: ${m.text()}`); });
  await p.goto(base);
  await p.waitForSelector('.post', { timeout: 20000 });
  await p.waitForTimeout(1500);
  await p.screenshot({ path: `${out}/01-top.png` });
  for (let i = 0; i < 6; i++) { await p.mouse.wheel(0, 700); await p.waitForTimeout(900); }
  await p.screenshot({ path: `${out}/02-scrolled.png` });
  const posts = await p.$$('.post');
  console.log('posts rendered', posts.length, 'windows', (await p.$$('.win')).length);
  const first = posts[2];
  await first.scrollIntoViewIfNeeded();
  await (await first.$('button[aria-label="Save"]')).click();
  await (await first.$('button[aria-label="Rate with flames"]')).click();
  await p.waitForTimeout(200);
  await (await first.$('input[type=range]')).fill('5');
  await p.waitForTimeout(700);
  await (await first.$('button[aria-label="Ask about this post"]')).click();
  await (await first.$('.askrow input')).fill('Is there a part 2?');
  await (await first.$('.askrow button')).click();
  await p.waitForTimeout(900);
  await first.screenshot({ path: `${out}/03-post-ask.png` });
  const comments = await first.$('button[aria-label="Comments"]');
  if (comments) { await comments.click(); await p.waitForTimeout(700); await first.screenshot({ path: `${out}/04-comments.png` }); }
  await (await first.$('.who')).click();
  await p.waitForTimeout(900);
  await first.screenshot({ path: `${out}/05-profile.png` });
  await p.fill('#askIn', 'quick gifs');
  await p.click('.ask button');
  await p.waitForTimeout(1500);
  console.log('askOut:', await p.textContent('#askOut'));
  console.log('crumbs:', await p.textContent('.crumbs'));
  await p.click('button[aria-label="Your map"]');
  await p.waitForTimeout(1200);
  await p.screenshot({ path: `${out}/06-map.png` });
  await p.click('button[aria-label="Memory"]');
  await p.waitForTimeout(1000);
  await p.fill('#newMem', 'Prefers slow builds over anything fast.');
  await p.click('.addmem button[type=submit]');
  await p.waitForTimeout(600);
  await p.click('text=Suggest new memories');
  await p.waitForTimeout(1500);
  await p.screenshot({ path: `${out}/07-memory.png` });
  await p.click('button[aria-label="Settings"]');
  await p.waitForTimeout(1500);
  await p.screenshot({ path: `${out}/08-settings.png` });
  await p.hover('.status');
  await p.waitForTimeout(600);
  await p.screenshot({ path: `${out}/09-status.png`, clip: { x: 640, y: 0, width: 800, height: 520 } });
  const m = await b.newPage({ viewport: { width: 390, height: 844 } });
  m.on('pageerror', (e) => errs.push(`mobile pageerror: ${e.message}`));
  await m.goto(base);
  await m.waitForSelector('.post', { timeout: 20000 });
  for (let i = 0; i < 8; i++) { await m.mouse.wheel(0, 800); await m.waitForTimeout(500); }
  await m.screenshot({ path: `${out}/10-mobile.png` });
  const overflow = await m.evaluate(() => document.documentElement.scrollWidth - window.innerWidth);
  console.log('mobile horizontal overflow px:', overflow, 'windows in feed:', (await m.$$('.feed .win')).length);
  console.log('ERRORS', JSON.stringify(errs, null, 1));
  await b.close();
})();
